SELECT TOP (1000) [Id]
      ,[Name]
      ,[Details]
      ,[Rate]
      ,[Sqft]
      ,[Occupancy]
      ,[ImageUrl]
      ,[Amenity]
      ,[CreatedDate]
      ,[UpdatedDate]
  FROM [master].[dbo].[Villas]
