// <auto-generated />
using CRUDIslemleri.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDIslemleri.Migrations
{
    [DbContext(typeof(CRUDIslemleriContext))]
    partial class CRUDIslemleriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDIslemleri.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<bool>("Gecti")
                        .HasColumnType("bit");

                    b.Property<int>("Not1")
                        .HasColumnType("int");

                    b.Property<int>("Not2")
                        .HasColumnType("int");

                    b.Property<int>("Not3")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciIsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("int");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.ToTable("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
